Updated  release to publish only on completed PR's to main branch, PROJECTS variable defining projects to run, trying out without running chmood +x for build.sh, added emulator/cross-compile checks for architectures for only the corresponding architecture, build test still runs for pushes to all branches

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,9 +2,18 @@ name: CI/CD Build For BeagleBone Black
 
 on:
   push:
-    branches: ["main", "12-create-cicd-pipeline-to-compile-and-lint-code"]
+    branches:
+      - '**'
   pull_request:
-    branches: ["main"]
+    branches:
+      - '**'
+    # PR Status's
+    types: [opened, synchronize, reopened, closed]
+
+# Project list
+env:
+  # Add more projects with space followed by project name, Ex: p1 p2 p3 ...
+  PROJECTS: "p1"
 
 jobs:
   # Job 1: Lint (clang formatting using v18.1.3)
@@ -22,7 +31,7 @@ jobs:
           echo "Checking code formatting..."
           find projects -name '*.c' -o -name '*.h' | xargs clang-format --dry-run --Werror --style=file
 
-  # Job 2: QEMU Integration and Build
+  # Job 2: QEMU Integration, Build Project, and Test Project
   build:
     needs: lint
     runs-on: ubuntu-24.04
@@ -60,49 +69,76 @@ jobs:
           gcc --version
 
           echo "QEMU Emulator Check"
-          qemu-system-arm --version || echo "qemu-system-arm not found"
-          qemu-system-aarch64 --version || echo "qemu-system-aarch64 not found"
-          qemu-system-ppc --version || echo "qemu-system-ppc not found"
+          if [ "${{ matrix.arch }}" == "arm" ]; then
+            qemu-system-arm --version || echo "qemu-system-arm not found"
+          elif [ "${{ matrix.arch }}" == "aarch64" ]; then
+            qemu-system-aarch64 --version || echo "qemu-system-aarch64 not found"
+          elif [ "${{ matrix.arch }}" == "powerpc" ]; then
+            qemu-system-ppc --version || echo "qemu-system-ppc not found"
+          elif [ "${{ matrix.arch }}" == "x86_64" ]; then
+            echo "Native x86_64 architecture: QEMU Emulator is not needed"
+          else
+            echo "Error: Unknown architecture '${{ matrix.arch }}' requested, exiting now..."
+            exit 1
+          fi
 
           echo "QEMU Cross-Compile Check"
-          arm-linux-gnueabihf-gcc --version || echo "arm-linux-gnueabihf-gcc not found"
-          aarch64-linux-gnu-gcc --version || echo "aarch64-linux-gnu-gcc not found"
-          powerpc-linux-gnu-gcc --version || echo "powerpc-linux-gnu-gcc not found"
+          if [ "${{ matrix.arch }}" == "arm" ]; then
+            arm-linux-gnueabihf-gcc --version || echo "arm-linux-gnueabihf-gcc not found"
+          elif [ "${{ matrix.arch }}" == "aarch64" ]; then
+            aarch64-linux-gnu-gcc --version || echo "aarch64-linux-gnu-gcc not found"
+          elif [ "${{ matrix.arch }}" == "powerpc" ]; then
+            powerpc-linux-gnu-gcc --version || echo "powerpc-linux-gnu-gcc not found"
+          elif [ "${{ matrix.arch }}" == "x86_64" ]; then
+            echo "Native x86_64 architecture: QEMU Cross-Compile is not needed, using gcc"
+          else 
+            echo "Error: Unknown architecture '${{ matrix.arch }}' requested, exiting now..."
+            exit 1
+          fi
 
       - name: Compile Target
         run: |
-          chmod +x build.sh
-          # NEED TO CHANGE PER PROJECT
-          ./build.sh --target p1 --arch ${{ matrix.arch }}
-
+          # Commented out for test
+          # chmod +x build.sh
+          for project in $PROJECTS; do
+            echo "---Compiling Project: $project"
+            ./build.sh --target $project --arch ${{ matrix.arch }}
+          done 
       - name: Test Target
         run: |
-          # NEED TO CHANGE PER PROJECT
-          if [ -f build/p1 ]; then
-            # TODO remove this for real implementation, but timemout after 10 seconds so it does not keep running forever
-            timeout --preserve-status 10s ./build/p1
+          # Loop through projects to run
+          for project in $PROJECTS; do
+            echo "---Testing target: $project---"
+            if [ -f "build/$project" ]; then
+              # TODO remove this for real implementation, but timemout after 10 seconds so it does not keep running forever
+              timeout --preserve-status 10s "./build/$project"
 
-            # Rename for artifact
-            mv build/p1 build/p1-${{ matrix.arch }}
-          else
-            echo "Error: Build not found"
-            exit 1
-          fi
-         
+              # Rename for artifact
+              mv "build/$project" "build/${project}-${{ matrix.arch }}"
+            else
+              echo "Error: Build not found for $project"
+              exit 1
+            fi
+          done
+
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: p1-binary-${{ matrix.arch }}
-          path: build/p1-${{ matrix.arch }}
+          name: project-binaries-${{ matrix.arch }}
+          # Grabs all artifacts made with project_name-architecture
+          path: build/*-${{ matrix.arch }}
           # Remove artifact files after a day, but latest builds will still be saved on release
           retention-days: 1
+
+
 
   # Job 3: Putting build files into release tab instead of temp storage artifacts
   release:
     needs: build
     runs-on: ubuntu-24.04
-    if: github.event_name == 'push'
-
+    # Publish artifacts to release if PR is completed
+    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
+  
     permissions:
       contents: write
 
@@ -111,23 +147,23 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           path: ./all-binaries
-          # NEED TO CHANGE PER PROJECT
-          pattern: p1-binary-*
+          pattern: project-binaries-*
           merge-multiple: true
 
       - name: Create Branch's Release
         uses: softprops/action-gh-release@v2
         with:
-          # Use branch name as tag
-          tag_name: latest-${{ github.ref_name }}
-          name: Release for branch ${{ github.ref_name }}
+          tag_name: latest-${{ github.base_ref }}
+          name: Release for branch ${{ github.base_ref }}
           body: |
-            Automated build for branch: ${{ github.ref_name }}
-            Last Updated: ${{ github.event.head_commit.timestamp }}
+            Automated build for merge to main from PR...
+            Source Branch: ${{ github.head_ref }}
+            Target Branch: ${{ github.base_ref }}
+            Merge Date: ${{ github.event.pull_request.merged_at }}
 
-          files: ./all-binaries/p1-*
+          files: ./all-binaries/*
 
-          prerelease: ${{ github.ref_name != 'main' }}
+          prerelease: ${{ github.base_ref != 'main' }}
           make_latest: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
